pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t hello-world-image .'
            }
        }

        stage('Deploy Docker Container') {
            steps {
                sh 'docker run --rm hello-world-image'
            }
        }
    }
}

